openapi: 3.0.4
info:
  title: Example API
  version: 1.0.0
  description: Example API
  contact:
    name: Example API
    url: https://example.com
    email: example@example.com
servers:
  - url: https://example.com
    description: Example API
tags:
  - name: Example
    description: Example
paths:
  /tags:
    get:
      summary: Get Tags
      description: Returns a list of tags
      operationId: GetTagList
      responses:
        "200":
          description: A list of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    description:
                      type: string
    post:
      summary: Create a new tag
      description: Creates a new tag
      operationId: CreateTag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
components:
  schemas:
    NewPost:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
